@version: 4.6
@include "scl.conf"

source s_syslog {
  syslog(
    transport(udp)
    ip(0.0.0.0)
    port(1514)
  );
};

destination d_http {
  http(
    url("http://redis-writer:1814/ingest")
    method("POST")
    headers("Content-Type: application/json")
    body("$(format-json --scope all-nv-pairs)")
  );
};

log {
  source(s_syslog);
  destination(d_http);
};
